version: '3.4'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile-nodeapp
    container_name: node-app
    ports:
      - 3000:3000
    volumes:
      - ./log:/var/log

  logstash:
    build:
      context: .
      dockerfile: Dockerfile-logstash
    container_name: logstash
    ports:
      - 41234:41234
    volumes:
      - ./log:/var/log

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    container_name: kibana
    ports:
      - 5601:5601
  
volumes:
  esdata1:
    driver: local
